---
# configure_ssh/tasks/compliance.yml

# The last task here always notifies the SSH restart handler

- name: "Install hardened config files (ssh_config, sshd_config)"
  ansible.builtin.copy:
    remote_src: false
    src: "{{ item }}"
    dest: "/etc/ssh/"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - ssh_config
    - sshd_config
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - molecule-idempotence-notest

- name: Set port (sshd_config)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^.Port.*$'
    line: Port {{ ssh_port }}
  become: true
  become_method: ansible.builtin.sudo

- name: "Install custom login banner"
  ansible.builtin.copy:
    remote_src: false
    src: issue
    dest: "/etc/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - issue
    - issue.net
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - molecule-idempotence-notest

- name: "Verify root is the group and owner of server ssh path"
  ansible.builtin.file:
    path: /etc/ssh
    owner: root
    group: root
    recurse: true
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server config files"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0600"
  loop:
    - /etc/ssh/ssh_config
    - /etc/ssh/sshd_config
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server public key files"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ssh_host_public_keys.files }}"
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server private key files"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ ssh_host_private_keys.files }}"
  become: true
  become_method: ansible.builtin.sudo
